apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tapcbdemo
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: mood-portal
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/component: run
    carto.run/workload-name: tapcbdemo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.4.5
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-portal
        apps.tanzu.vmware.com/workload-type: dekt-url
        carto.run/workload-name: tapcbdemo
        conventions.apps.tanzu.vmware.com/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.tanzuworld.com/tap-stage/tapcbdemo-myapps@sha256:fdbcfd58db67b28ddcb14f274a06435ba3d15d146af9d7023c88b48279288e89
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

