apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mood-portal
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: mood-portal
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-portal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-portal
        apps.tanzu.vmware.com/workload-type: dekt-url
        carto.run/workload-name: mood-portal
    spec:
      containers:
      - env:
        - name: SNIFF_THRESHOLD
          value: "20"
        - name: SENSORS_ACTIVATE_API
          value: http://mood-sensors.prod.openso.online/activate
        - name: SENSORS_MEASURE_API
          value: http://mood-sensors.prod.openso.online/measure
        image: openso.azurecr.io/tap-stage/mood-portal-apps@sha256:923f7b5e85c065efb63fcdb19c4f7cdb92718d72bb3bf3bd6fb4168167fc834c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

