apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-analyzer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: mood-analyzer
    apps.tanzu.vmware.com/workload-type: dekt-worker
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-analyzer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: mood-analyzer
      apps.tanzu.vmware.com/workload-type: dekt-worker
      carto.run/workload-name: mood-analyzer
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-analyzer
        apps.tanzu.vmware.com/workload-type: dekt-worker
        carto.run/workload-name: mood-analyzer
    spec:
      containers:
      - image: harbor.tanzuworld.com/tap-stage/mood-analyzer-myapps@sha256:339b079a1ec87006f5160fc91e5636b8e92091914b3afab95a166e264e050be0
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

