apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: openso-tapcbdemo
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: cbdemo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: openso
    app.kubernetes.io/component: run
    carto.run/workload-name: openso-tapcbdemo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.4.5
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: cbdemo
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: openso
        carto.run/workload-name: openso-tapcbdemo
        conventions.apps.tanzu.vmware.com/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.tanzuworld.com/tap-stage/openso-tapcbdemo-myapps@sha256:a6f1b1ddcaa3c755074dc8d962196558fdc73d88656ef87286ef694176d580ae
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

